"""empty message

Revision ID: 185fe660231d
Revises: 2633f344f5db
Create Date: 2023-02-13 14:26:55.074060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185fe660231d'
down_revision = '2633f344f5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
        batch_op.alter_column('categories',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('categories',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
        batch_op.alter_column('tags',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))

    # ### end Alembic commands ###
