"""empty message

Revision ID: 67eb78031a43
Revises: 758d12847f80
Create Date: 2023-02-13 09:39:15.101150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67eb78031a43'
down_revision = '758d12847f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('slug', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))
        batch_op.drop_constraint('categories_category_key', type_='unique')
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.create_unique_constraint(None, ['name'])
        # batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('categories_category_key', ['category'])
        batch_op.drop_column('count')
        batch_op.drop_column('slug')
        batch_op.drop_column('name')

    op.drop_table('tags')
    # ### end Alembic commands ###
